services:
  - type: web
    name: prompt-stack-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.prod
    dockerContext: .
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false